version: '3.8'

services:
  # Next.js Web Application
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: maha-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost}
    volumes:
      - ./branding:/app/public/branding:ro
    networks:
      - maha-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: maha-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./branding:/usr/share/nginx/html/branding:ro
    depends_on:
      - web
      - headstart
      - eviatlas
    networks:
      - maha-network
    restart: unless-stopped

  # Headstart Service (Open Knowledge Maps)
  headstart:
    build:
      context: ./apps/headstart
      dockerfile: Dockerfile
    container_name: maha-headstart
    environment:
      - NODE_ENV=production
    volumes:
      - ./branding:/app/branding:ro
    networks:
      - maha-network
    restart: unless-stopped

  # EviAtlas Service
  eviatlas:
    build:
      context: ./apps/eviatlas
      dockerfile: Dockerfile
    container_name: maha-eviatlas
    environment:
      - R_ENV=production
    volumes:
      - ./data/seeds:/srv/shiny-server/data:ro
      - ./branding:/srv/shiny-server/branding:ro
    networks:
      - maha-network
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: maha-redis
    networks:
      - maha-network
    restart: unless-stopped

networks:
  maha-network:
    driver: bridge

volumes:
  redis-data:
