name: Ingestion Sync

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ingestion pipelines
        run: python data/ingestion/pipelines.py
